"""
Database models for Meta Targeting Optimizer.
"""
from sqlalchemy import Column, Integer, String, Float, Boolean, Text, DateTime, JSON, Index
from sqlalchemy.sql import func
from app.core.database import Base


class MetaTargetingRecommendationModel(Base):
    """
    Stores targeting recommendations generated by the optimizer.
    """
    __tablename__ = "meta_targeting_recommendations"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    run_id = Column(String(36), nullable=False, index=True)  # UUID from optimization run
    
    # Target entities
    campaign_id = Column(String(50), nullable=False, index=True)
    adset_id = Column(String(50), nullable=False, index=True)
    
    # Recommendation payload (JSON)
    targeting_spec = Column(JSON, nullable=False)
    reasoning = Column(JSON, nullable=True)
    
    # Expected performance
    expected_ctr = Column(Float, default=0.0)
    expected_cvr = Column(Float, default=0.0)
    expected_roas = Column(Float, default=0.0)
    confidence = Column(Float, default=0.0)
    
    # Status
    status = Column(String(20), default="pending")  # pending, applied, rejected
    applied_at = Column(DateTime, nullable=True)
    
    # Metadata
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Indexes for performance
    __table_args__ = (
        Index("idx_targeting_rec_run_campaign", "run_id", "campaign_id"),
        Index("idx_targeting_rec_status_created", "status", "created_at"),
    )


class MetaTargetingHistoryModel(Base):
    """
    Audit log of all targeting changes applied to adsets.
    """
    __tablename__ = "meta_targeting_history"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    run_id = Column(String(36), nullable=False, index=True)
    recommendation_id = Column(Integer, nullable=True)  # FK to recommendations
    
    # Target entities
    campaign_id = Column(String(50), nullable=False, index=True)
    adset_id = Column(String(50), nullable=False, index=True)
    
    # Change details
    old_targeting = Column(JSON, nullable=True)
    new_targeting = Column(JSON, nullable=False)
    
    # Performance tracking (before/after)
    before_ctr = Column(Float, nullable=True)
    before_cvr = Column(Float, nullable=True)
    before_roas = Column(Float, nullable=True)
    
    after_ctr = Column(Float, nullable=True)
    after_cvr = Column(Float, nullable=True)
    after_roas = Column(Float, nullable=True)
    
    # Status
    success = Column(Boolean, default=True)
    error_message = Column(Text, nullable=True)
    
    # Applied by
    applied_by = Column(String(100), nullable=True)  # user or "auto_optimizer"
    mode = Column(String(10), default="stub")  # stub | live
    
    # Timestamps
    applied_at = Column(DateTime, server_default=func.now(), nullable=False)
    performance_measured_at = Column(DateTime, nullable=True)
    
    # Indexes
    __table_args__ = (
        Index("idx_targeting_hist_adset_applied", "adset_id", "applied_at"),
        Index("idx_targeting_hist_campaign", "campaign_id"),
        Index("idx_targeting_hist_run", "run_id"),
    )


class MetaTargetingSegmentScoreModel(Base):
    """
    Stores computed scores for segments (interests, behaviors, geos, etc).
    Updated daily by the optimizer.
    """
    __tablename__ = "meta_targeting_segment_scores"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Segment identification
    segment_id = Column(String(100), nullable=False, index=True, unique=True)
    segment_name = Column(String(255), nullable=False)
    segment_type = Column(String(50), nullable=False)  # interest, behavior, geo, demographic
    
    # Raw metrics
    impressions = Column(Integer, default=0)
    clicks = Column(Integer, default=0)
    conversions = Column(Integer, default=0)
    spend = Column(Float, default=0.0)
    revenue = Column(Float, default=0.0)
    
    # Computed metrics
    ctr = Column(Float, default=0.0)
    cvr = Column(Float, default=0.0)
    roas = Column(Float, default=0.0)
    
    # Bayesian smoothed scores
    bayesian_ctr = Column(Float, default=0.0)
    bayesian_cvr = Column(Float, default=0.0)
    bayesian_roas = Column(Float, default=0.0)
    
    # Weighted composite score
    composite_score = Column(Float, default=0.0)
    confidence = Column(Float, default=0.0)
    
    # Ranking
    rank = Column(Integer, nullable=True, index=True)
    
    # Fatigue detection
    is_fatigued = Column(Boolean, default=False, index=True)
    fatigue_reason = Column(Text, nullable=True)
    
    # Usage stats
    campaigns_used_count = Column(Integer, default=0)
    last_used_at = Column(DateTime, nullable=True)
    
    # Metadata
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())
    
    # Indexes for performance
    __table_args__ = (
        Index("idx_segment_score_type_score", "segment_type", "composite_score"),
        Index("idx_segment_score_fatigued", "is_fatigued"),
        Index("idx_segment_score_rank", "rank"),
    )
